### ISSUE TITLE
Expected redirect response from (http://learningequality.org/r/translationmapping)

### ISSUE THREAD

**Issue by mrpau-eugene** [learningequality/ka-lite-content-packs#77]
I'm getting this error when trying to build content packs

```
INFO:root:Getting spreadsheet location from (http://learningequality.org/r/translationmapping)
Traceback (most recent call last):
  File "/Users/yujin/Desktop/ka-lite-content-packs/contentpacks/generate_dubbed_video_mappings.py", line 51, in download_ka_dubbed_video_csv
    download_url = urllib.request.urlopen(csv_url).geturl()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/yujin/Desktop/ka-lite-content-packs/contentpacks/__main__.py", line 119, in <module>
    main()
  File "/Users/yujin/Desktop/ka-lite-content-packs/contentpacks/__main__.py", line 108, in main
    make_language_pack(lang, version, sublangs, out, ka_domain, no_assessment_items, no_subtitles, no_assessment_resources, no_dubbed_videos)
  File "/Users/yujin/Desktop/ka-lite-content-packs/contentpacks/__main__.py", line 35, in make_language_pack
    node_data, subtitle_data, interface_catalog, content_catalog = retrieve_language_resources(version, sublangargs, ka_domain, no_subtitles, no_dubbed_videos)
  File "/Users/yujin/Desktop/ka-lite-content-packs/contentpacks/khanacademy.py", line 126, in retrieve_language_resources
    node_data = retrieve_kalite_data(lang=sublangargs["content_lang"], force=True, ka_domain=ka_domain, no_dubbed_videos=no_dubbed_videos)
  File "/Users/yujin/Desktop/ka-lite-content-packs/contentpacks/khanacademy.py", line 633, in retrieve_kalite_data
    node_data = add_dubbed_video_mappings(node_data, lang)
  File "/Users/yujin/Desktop/ka-lite-content-packs/contentpacks/khanacademy.py", line 646, in add_dubbed_video_mappings
    main()
  File "/Users/yujin/Desktop/ka-lite-content-packs/contentpacks/generate_dubbed_video_mappings.py", line 158, in main
    csv_data = download_ka_dubbed_video_csv(cache_filepath=CACHE_FILEPATH)
  File "/Users/yujin/Desktop/ka-lite-content-packs/contentpacks/generate_dubbed_video_mappings.py", line 58, in download_ka_dubbed_video_csv
    raise Exception("Expected redirect response from (%s)" % csv_url)
Exception: Expected redirect response from (http://learningequality.org/r/translationmapping)
```

Will look into this and fix the problem asap

**Comment by benjaoming** [comment]
This must have happened while upgrades of website and cloudflare integration caused instability! It works now :)

**Comment by mrpau-eugene** [comment]
@benjaoming it was fixed during my last PR. I just used the `requests` module.
